Updated the Readme
bharat94/Git-AI-Grader pull request #12
Opened 2018-02-11 18:17 UTC by tripathiamritansh

2018-02-11 21:59 UTC, bharat94 requested changes
Please change the license type

2018-02-11 21:59 UTC, bharat94 commented on README.md
> +This project is licensed under the MIT License.
Not the MIT license but GNU GPL 3.0

2018-02-11 23:02 UTC, tripathiamritansh commented
@bharat94 addressed PR comment

2018-02-12 06:18 UTC, bharat94 approved these changes

2018-02-12 06:18 UTC, merged